name : CI

on:
  push:
    branches: [ master ]
  # pull_request:
  #  branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ## git action 서버 설정
      - uses: actions/checkout@v2

      ## node cache 적용
      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      ## node 연관 dependency 설치
      - name: Install Dependencies
        run: npm install

      ## docker part
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: teichae/node
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
            
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1    
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Docker Build and Dockerhub Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: menofdocker/mos-main-client:latest
          cache-from: type=gha # 여기서 gha 는 Guthub Actions 용 캐시를 의미합니다.
          cache-to: type=gha,mode=max

      - name: Connect MenOfSillim
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            echo "Remove Container ID"
            if [ $(docker ps -af "name=mos-main-client" -q | awk '{print length}') -gt 1 ]
            then
              echo "Container Exist"
              docker rm -f $(docker ps -af "name=mos-main-client" -q)
            else
              echo "Container No Exist"
            fi

            echo "Remove Image ID"
            if [ $(docker images -f "reference=**/mos-main-client" -q | awk '{print length}') -gt 1 ]
            then
              echo "Image Exist"
              docker rmi -f menofdocker/mos-main-client:latest
            else
              echo "Image No Exist"
            fi

            echo "Pull Docker Image"
            docker pull menofdocker/mos-main-client:latest

            echo "Run Docker Image"
            docker run -d --name mos-main-client \
                       -p 30040:3000 \
                       --add-host=host.docker.internal:host-gateway \
                       --restart unless-stopped menofdocker/mos-main-client
